version: "3"
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-app
    container_name: app
    restart: unless-stopped
    tty: true
    depends_on:
      - db
    environment:
      SERVICE_NAME: app
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - vendor:/var/www/vendor
      - ./conf/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Scheduler
  scheduler:
    image: php-app
    depends_on:
      - app
      - webserver
      - db
    container_name: scheduler
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - vendor:/var/www/vendor
      - ./conf/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    command: sh .bin/run-scheduler.sh
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    depends_on:
      - app
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./conf/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  # MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    env_file: .env
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    volumes:
      - dbdata:/var/lib/mysql/
      # - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  vendor:
  dbdata:
    driver: local
